services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api-server
  api-server:
    build:
      context: .
      dockerfile: ./dockerfiles/api-server.Dockerfile
    ports:
      - 4664:4664