// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NOTE: When adding a new invoke command,
 * the label should match up to the tauri generated command names.
 */
export type ClientInvoke = "ask_clippy" | "authorize_connection" | "choose_folder" | "copy_to_clipboard" | "default_indices" | "escape" | "open_plugins_folder" | "get_library_stats" | "get_shortcut" | "get_startup_progress" | "install_lens" | "list_connections" | "list_installed_lenses" | "list_installable_lenses" | "list_plugins" | "load_user_settings" | "load_action_settings" | "open_big_mode" | "open_folder_path" | "open_lens_folder" | "open_result" | "open_settings_folder" | "resize_window" | "resync_connection" | "revoke_connection" | "run_lens_updater" | "save_user_settings" | "search_docs" | "search_lenses" | "uninstall_lens" | "update_and_restart" | "wizard_finished" | "navigate";
