// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextFilter } from "./ContextFilter";
import type { UserActionDefinition } from "./UserActionDefinition";

export type ContextActions = { context: ContextFilter, actions: Array<UserActionDefinition>, };
