// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextFilter = { has_tag: Array<[string, string]> | null, has_tag_type: Array<string> | null, exclude_tag: Array<[string, string]> | null, exclude_tag_type: Array<string> | null, url_like: Array<string> | null, };
