// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormType = "Bool" | "Number" | "Path" | "PathList" | "StringList" | "Text" | "KeyBinding";
