// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallStatus = "NotInstalled" | { "Finished": { num_docs: number, } } | { "Installing": { percent: number, status: string, } };
