// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallableLens = { author: string, description: string, name: string, label: string, sha: string, download_url: string, html_url: string, categories: Array<string>, };
