// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallStatus } from "./InstallStatus";
import type { LensType } from "./LensType";

export type LensResult = { 
/**
 * Author of this lens
 */
author: string, 
/**
 * Unique identifier
 */
name: string, 
/**
 * Human readable label
 */
label: string, 
/**
 * Huamn readable description of the lens
 */
description: string, 
/**
 * Used to determine whether a lens needs an update
 */
hash: string, 
/**
 * For installed lenses.
 */
file_path: string | null, categories: Array<string>, html_url: string | null, download_url: string | null, progress: InstallStatus, lens_type: LensType, };
