// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportedConnection } from "./SupportedConnection";
import type { UserConnection } from "./UserConnection";

export type ListConnectionResult = { supported: Array<SupportedConnection>, user_connections: Array<UserConnection>, };
