// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchResult = { 
/**
 * Document ID
 */
doc_id: string, 
/**
 * URI used to crawl this result
 */
crawl_uri: string, domain: string, title: string, description: string, url: string, tags: Array<[string, string]>, score: number, };
