// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMeta } from "./SearchMeta";
import type { SearchResult } from "./SearchResult";

export type SearchResults = { results: Array<SearchResult>, meta: SearchMeta, };
