// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchResultTemplate = { 
/**
 * Document ID
 */
doc_id: string, 
/**
 * URI used to crawl this result
 */
crawl_uri: string, domain: string, title: string, description: string, url: string, open_url: string, tags: Array<[string, string]>, score: number, url_schema: string, url_userinfo: string, url_parent: string, url_port: number, url_path: Array<string>, url_path_length: number, url_query: string, };
