// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormType } from "./FormType";

export type SettingOpts = { label: string, value: string, form_type: FormType, help_text: string | null, restart_required: boolean, };
