// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserAction } from "./UserAction";

export type UserActionDefinition = { label: string, status_msg: string | null, action: UserAction, key_binding: string, };
